// GOVERNANCE: Read docs/governance/04-GOVERNANCE.md before editing this file. (See sec.0 for mandatory pre-edit checklist.)
/**
 * `/.well-known/` — the association files the OS reads, not the app.
 *
 * ── Why this exists at all ─────────────────────────────────────────────────
 * Player sign-in is a one-time link the bot sends as
 * `${PUBLIC_APP_ORIGIN}/#/auth/telegram?token=…`. Before this file existed the
 * installed APK had only a MAIN/LAUNCHER intent-filter, so Android had no
 * reason to believe that URL belonged to the app: tapping it opened a browser,
 * the browser redeemed the single-use token into ITS OWN storage, and the app
 * the player had just installed stayed signed out with no way to recover —
 * every fresh link repeats the same journey. An Android App Link is the only
 * mechanism the platform offers to route that tap to the app instead, and
 * Digital Asset Links is how the platform decides the claim is genuine.
 *
 * ── Why it is generated rather than committed ──────────────────────────────
 * The file names the app's signing certificate. That fingerprint is a property
 * of a keystore that (per ANDROID_RELEASE_SETUP.md) is generated by the owner
 * and never enters this repository, so it cannot be a static asset here — it
 * is deployment configuration, exactly like PUBLIC_APP_ORIGIN, and it lives
 * with the rest of it.
 *
 * ── Why the fingerprint is a LIST ──────────────────────────────────────────
 * Not future-proofing. Under Google Play App Signing the APK that reaches a
 * handset is re-signed by Google, so the certificate the OS sees is NOT the
 * upload certificate — a site listing only the upload fingerprint verifies for
 * sideloaded builds and silently fails for every Play install. Both belong
 * here. The same list carries an old fingerprint through a key rotation.
 *
 * ── Why an unset fingerprint is 404 and not an empty document ──────────────
 * An empty `[]` is a positive statement — "this site vouches for no app" —
 * which Android caches as a verification FAILURE. A 404 is the honest answer
 * ("nothing is published yet") and leaves the next verification attempt free
 * to succeed once the value is set.
 */
import express from 'express';
import { csv } from '../startup/validateEnv.js';

const router = express.Router();

/** Android accepts uppercase colon-separated hex; normalise so either form works. */
function normaliseFingerprint(value) {
  const hex = String(value).replace(/[^0-9a-fA-F]/g, '').toUpperCase();
  if (hex.length !== 64) return null;                       // SHA-256 = 32 bytes
  return hex.match(/.{2}/g).join(':');
}

/**
 * Digital Asset Links — proves to Android that this site vouches for the app,
 * which is what turns the intent-filter in AndroidManifest.xml from a claim
 * into a VERIFIED App Link (no disambiguation dialog, no user opt-in step).
 *
 * Served from the backend rather than as a static file under dist/ so it
 * follows PUBLIC_APP_ORIGIN across deployments and cannot drift from the
 * package id already advertised by /api/app/bootstrap.
 */
router.get('/assetlinks.json', (req, res) => {
  const packageName = process.env.ANDROID_PACKAGE_ID;
  const fingerprints = csv(process.env.ANDROID_SHA256_CERT_FINGERPRINTS)
    .map(normaliseFingerprint)
    .filter(Boolean);

  if (!packageName || fingerprints.length === 0) {
    return res.status(404).json({
      success: false,
      message: 'No Android application is associated with this origin.',
    });
  }

  // Android fetches this over HTTPS with no redirects and requires
  // application/json. res.json() sets that; the no-redirect part is the
  // deployment's job (see ANDROID_RELEASE_SETUP.md).
  res.json([
    {
      // Exactly one relation, deliberately. `handle_all_urls` is what App Link
      // verification reads and all this app needs.
      //
      // `delegate_permission/common.get_login_creds` is the other relation
      // commonly pasted in alongside it, and it does NOT belong here: it lets
      // the app pull credentials the browser saved for this ORIGIN. Players
      // have no password (auth is a one-time Telegram link), so it buys
      // nothing — while the admin and merchant panels are served from this
      // same origin and their operators do save passwords for it. Granting the
      // player APK a claim on those is a real widening for zero benefit.
      relation: ['delegate_permission/common.handle_all_urls'],
      target: {
        namespace: 'android_app',
        package_name: packageName,
        sha256_cert_fingerprints: fingerprints,
      },
    },
  ]);
});

export default router;
