import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import '../design-system/variables.css';
import CommandPalette from '../components/CommandPalette.jsx';
import NotificationCenter from '../components/NotificationCenter.jsx';
import RealtimeStatus from '../components/RealtimeStatus.jsx';
const merchantLinks=[['Dashboard','/merchant/dashboard'],['Orders','/merchant/orders'],['History','/merchant/history'],['Payouts','/merchant/payouts'],['Profile','/merchant/profile']];
export default function MerchantPanelShell({ children, title = 'Merchant Workspace' }) {
  const [mobileNavOpen,setMobileNavOpen]=useState(false);
  const nav=<nav aria-label="Merchant navigation" style={{ padding:16, borderRight:'1px solid var(--bb-border)' }}>{merchantLinks.map(([label,path])=><Link className="bb-focus" key={label} to={path} style={merchantNav}>{label}</Link>)}</nav>;
  return <div style={{ minHeight:'100dvh', background:'var(--bb-navy-950)', color:'var(--bb-text)' }}><header style={{ height:64, display:'flex', alignItems:'center', justifyContent:'space-between', padding:'0 20px', borderBottom:'1px solid var(--bb-border)', background:'var(--bb-navy-900)' }}><b>BB MERCHANT</b><div style={{display:'flex',gap:8,alignItems:'center'}}><button className="bb-focus merchant-mobile-nav-button" onClick={()=>setMobileNavOpen(v=>!v)} aria-expanded={mobileNavOpen}>Menu</button><RealtimeStatus/><CommandPalette panel="merchant"/><NotificationCenter panel="merchant"/></div></header><div style={{ display:'grid', gridTemplateColumns:'220px minmax(0,1fr)', minHeight:'calc(100dvh - 64px)' }}>{nav}<main style={{ minWidth:0, overflow:'auto', padding:'clamp(16px,3vw,32px)' }}><h1>{title}</h1>{mobileNavOpen&&<div className="merchant-mobile-nav">{nav}</div>}{children}</main></div><div className="merchant-mobile-actions" aria-label="Merchant quick actions"><button>Accept</button><button>Reject</button><button>Chat</button><button>Upload proof</button><button>Complete</button></div><style>{`.merchant-mobile-actions,.merchant-mobile-nav-button,.merchant-mobile-nav{display:none}@media(max-width:700px){div[style*="220px"]{grid-template-columns:1fr!important}div[style*="220px"]>nav{display:none}.merchant-mobile-nav-button{display:inline-flex}.merchant-mobile-nav{display:block}.merchant-mobile-actions{position:sticky;bottom:0;display:grid!important;grid-template-columns:repeat(5,1fr);gap:4px;padding:8px;background:var(--bb-navy-900);border-top:1px solid var(--bb-border)}.merchant-mobile-actions button{min-height:48px;border:0;border-radius:8px;background:var(--bb-surface-raised);color:var(--bb-text);font-size:11px}}`}</style></div>;
}
const merchantNav={display:'block',width:'100%',border:0,borderRadius:8,padding:12,marginBottom:4,textAlign:'left',background:'transparent',color:'var(--bb-text-muted)',cursor:'pointer',textDecoration:'none'};
