// GOVERNANCE: Read docs/governance/04-GOVERNANCE.md before editing this file. (See sec.0 for mandatory pre-edit checklist.)
/**
 * domains/referral/referral.model.js — the two-tier referral programme.
 *
 * ── The rule ────────────────────────────────────────────────────────────────
 * When a new user completes onboarding, TWO earnings may be generated:
 *
 *     A refers B          →  A earns ₹25            (level 1)
 *     B refers C          →  B earns ₹25 (level 1)
 *                            A earns ₹25 (level 2)
 *     C refers D and E    →  C earns ₹25 each (level 1)
 *                            B earns ₹25 each (level 2)
 *                            A earns nothing — the tree stops at two levels
 *
 * So an earning is always generated BY a joining user, and paid TO that user's
 * referrer (level 1) and their referrer's referrer (level 2). Nothing deeper.
 *
 * ── Why the queue is keyed on the JOINER, not the earner ────────────────────
 * Rewards are paid from a pool an admin tops up, and the order they are paid in
 * has to be defensible. Ordering by the EARNER would pay the earliest joiners
 * forever — a user who joined first and keeps referring would drain every pool
 * ahead of everyone else. Ordering by the JOINING USER's unique joining number
 * makes the queue strictly first-in-first-out across the whole platform: a
 * referral made today is paid after every referral made before it, regardless
 * of who earns it. That is what `queuePosition` holds, and why it is copied
 * from the source user rather than from the earner.
 *
 * ── Eligibility is decided at PAYOUT, not at earning ────────────────────────
 * An earning is recorded the moment it is generated, but whether it is PAID
 * depends on facts that can change: the earner's KYC must have come back
 * VERIFIED, the earner must still be in the channel with the number they
 * verified, and the SOURCE user's KYC must have passed too — a failed KYC
 * anywhere invalidates the commissions it generated. Deciding this at payout
 * time is what lets the dashboard show a player exactly why a commission is
 * sitting unpaid instead of silently dropping it.
 */
import mongoose from 'mongoose';

/** ₹25 per referral event, in paise — money is integer paise everywhere. */
export const REFERRAL_REWARD_PAISE = 2500;

/** Programme ceilings, in the units they are enforced in. */
export const PROGRAMME_BUDGET_PAISE = 400_00_00_000_00; // ₹400 crore
export const PROGRAMME_MEMBER_CAP   = 8_00_00_000;      // 8 crore verified members

// ═══════════════════════════════════════════════════════════════════════════
// REFERRAL EARNING — one row per (joining user, level)
// ═══════════════════════════════════════════════════════════════════════════
const referralEarningSchema = new mongoose.Schema({
  // Who gets paid.
  earnerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  // Whose joining generated it.
  sourceUserId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  level: { type: Number, enum: [1, 2], required: true },

  amountPaise: { type: Number, required: true, default: REFERRAL_REWARD_PAISE },

  // The source user's unique joining number. THE queue key — see the header.
  queuePosition: { type: Number, required: true, index: true },

  status: {
    type: String,
    enum: ['PENDING', 'DISBURSED', 'BLOCKED'],
    default: 'PENDING',
    index: true,
  },
  // Why a row was skipped, in words a support agent can repeat to a player.
  blockedReason: { type: String, default: '' },

  disbursalBatchId: { type: String, default: null, index: true },
  disbursedAt:      { type: Date },
  // The wallet movement that paid it. Deterministic, so a re-run of a disbursal
  // cannot credit twice — the wallet authority's own idempotency does the rest.
  walletTxId:       { type: String, default: null },

  createdAt: { type: Date, default: Date.now, index: true },
}, { collection: 'referral_earnings' });

// ── The no-double-credit rule, enforced by the database ────────────────────
// One joining user generates at most ONE level-1 and ONE level-2 earning, ever.
// A replayed onboarding, a concurrent duplicate, or a retried job collides here
// instead of minting a second ₹25. This is the same shape the bet and wallet
// paths use: the unique index IS the gate, not a check-then-insert.
referralEarningSchema.index(
  { sourceUserId: 1, level: 1 },
  { unique: true, name: 'one_earning_per_source_level' },
);

// The disbursal query: everything payable, in queue order. Level ascends within
// a position so level 1 is always paid before level 2 for the same joiner.
referralEarningSchema.index({ status: 1, queuePosition: 1, level: 1 });
// A player's own earnings report.
referralEarningSchema.index({ earnerId: 1, createdAt: -1 });

// ═══════════════════════════════════════════════════════════════════════════
// DISBURSAL BATCH — one admin top-up, and what it paid for
// ═══════════════════════════════════════════════════════════════════════════
const referralDisbursalSchema = new mongoose.Schema({
  batchId: { type: String, required: true, unique: true, index: true },
  // What the admin authorised. The engine pays down the queue until this is
  // exhausted; it never pays a partial ₹25.
  poolPaise:  { type: Number, required: true },
  spentPaise: { type: Number, default: 0 },

  paidCount:    { type: Number, default: 0 },
  blockedCount: { type: Number, default: 0 },

  // How far down the queue this batch reached — the resume point, and what the
  // dashboard shows as "paid up to joiner #N".
  lastQueuePosition: { type: Number, default: 0 },

  actorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  status: {
    type: String,
    enum: ['RUNNING', 'COMPLETED', 'FAILED'],
    default: 'RUNNING',
    index: true,
  },
  error: { type: String, default: '' },

  createdAt:   { type: Date, default: Date.now, index: true },
  completedAt: { type: Date },
}, { collection: 'referral_disbursals' });

// ═══════════════════════════════════════════════════════════════════════════
// PROGRAMME COUNTERS — one document, the ceilings live here
// ═══════════════════════════════════════════════════════════════════════════
/**
 * The ₹400 crore budget and the 8 crore member cap are programme-wide limits,
 * so they need one place that can be read and incremented atomically. Deriving
 * them by summing every earning would be correct and unusably slow at the
 * member counts this programme is sized for.
 */
const referralProgrammeSchema = new mongoose.Schema({
  key: { type: String, default: 'main', unique: true, index: true },

  budgetPaise:    { type: Number, default: PROGRAMME_BUDGET_PAISE },
  disbursedPaise: { type: Number, default: 0 },
  memberCap:      { type: Number, default: PROGRAMME_MEMBER_CAP },
  // Members counted against the cap: onboarded AND KYC-verified.
  verifiedMembers: { type: Number, default: 0 },

  // An admin can pause payouts without unwinding anything.
  active: { type: Boolean, default: true },

  updatedAt: { type: Date, default: Date.now },
}, { collection: 'referral_programme' });

// ═══════════════════════════════════════════════════════════════════════════
// COUNTER — the atomic source of unique joining numbers
// ═══════════════════════════════════════════════════════════════════════════
/**
 * Joining numbers must be unique and strictly increasing, because the payout
 * queue is ordered by them. `findOneAndUpdate({$inc})` on a single document is
 * atomic in MongoDB, so two simultaneous signups cannot receive the same
 * number — the same reason it is used for invoice numbers everywhere.
 */
const counterSchema = new mongoose.Schema({
  key:   { type: String, required: true, unique: true, index: true },
  value: { type: Number, default: 0 },
}, { collection: 'counters' });

export const ReferralEarning   = mongoose.model('ReferralEarning', referralEarningSchema);
export const ReferralDisbursal = mongoose.model('ReferralDisbursal', referralDisbursalSchema);
export const ReferralProgramme = mongoose.model('ReferralProgramme', referralProgrammeSchema);
export const Counter           = mongoose.model('Counter', counterSchema);
