import React, { useEffect, useMemo, useRef, useState } from 'react';
const defaults = ['Users','Orders','Transactions','Games','Merchants','Settings','Reports','Pages'];
export default function CommandPalette({ panel = 'player', entries = defaults }) {
  const [open,setOpen]=useState(false), [query,setQuery]=useState(''), [active,setActive]=useState(0);
  const input=useRef(null); const recents=useMemo(()=>entries.slice(0,3),[entries]);
  const results=entries.filter(item=>item.toLowerCase().includes(query.toLowerCase()));
  useEffect(()=>{ const key=e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(true)} if(e.key==='Escape')setOpen(false)}; window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
  useEffect(()=>{if(open) setTimeout(()=>input.current?.focus(),0)},[open]);
  if(!open) return <button className="bb-focus" onClick={()=>setOpen(true)} style={trigger} aria-label="Search and commands">⌘K <span>Search</span></button>;
  return <div role="dialog" aria-modal="true" aria-label={`${panel} command palette`} onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)} style={overlay}><div className="bb-panel bb-glass" style={dialog}><input ref={input} value={query} onChange={e=>{setQuery(e.target.value);setActive(0)}} onKeyDown={e=>{if(e.key==='ArrowDown')setActive(i=>Math.min(i+1,Math.max(0,results.length-1)));if(e.key==='ArrowUp')setActive(i=>Math.max(i-1,0));if(e.key==='Enter'&&results[active])setOpen(false)}} placeholder="Search users, orders, pages, settings…" style={search}/><small style={hint}>{query?'Results':'Recent searches'} · ↑↓ navigate · Enter open · Esc close</small>{(query?results:recents).length ? (query?results:recents).map((item,i)=><button key={item} className="bb-focus" onClick={()=>setOpen(false)} style={{...itemStyle,background:i===active?'var(--bb-surface-raised)':'transparent'}}>{item}<span>Open</span></button>) : <div style={empty}><b>No results for “{query}”</b><span>Try an order ID, page name, operator, or setting.</span></div>}</div></div>;
}
const trigger={border:'1px solid var(--bb-border)',borderRadius:8,background:'var(--bb-surface)',color:'var(--bb-text-muted)',padding:'0 12px',cursor:'pointer'};
const overlay={position:'fixed',inset:0,zIndex:100,display:'grid',placeItems:'start center',paddingTop:'min(16vh,128px)',background:'rgba(0,0,0,.6)',backdropFilter:'blur(6px)'};
const dialog={width:'min(640px,calc(100vw - 24px))',padding:12}; const search={width:'100%',border:0,outline:0,borderRadius:8,padding:16,background:'var(--bb-navy-950)',color:'var(--bb-text)',fontSize:16}; const hint={display:'block',padding:'10px 8px',color:'var(--bb-text-subtle)'}; const itemStyle={width:'100%',minHeight:48,display:'flex',justifyContent:'space-between',alignItems:'center',border:0,borderRadius:8,color:'var(--bb-text)',padding:'0 12px',textAlign:'left',cursor:'pointer'}; const empty={display:'grid',gap:6,padding:24,color:'var(--bb-text-muted)'};
